# docker-compose.yml
version: '3'
services:
  ve:
    build:
      context: ./
      dockerfile: Dockerfile
    image: llvm-ve:latest
    container_name: llvm-ve-compiler
    user: $UID_GID
    working_dir: /src
    stdin_open: true
    volumes:
      - ./:/src
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    tty: true
    #command: tail -f /dev/null
